"""
Out-of-State Opponent Record Scraper
======================================
 
Fills the last missing input for the District Points Calculator: an
out-of-state opponent's win/loss record. We can't compute this ourselves
(we only see out-of-state teams through the handful of MSHSAA games they
play, nowhere near their real season), but MSHSAA displays it directly on
every in-state team's own schedule page, right next to the opponent's name
-- e.g. "Trinity Catholic (KY) (3-1)". This script visits only the in-state
teams that actually play an out-of-state opponent (a known, computed list,
not all ~300 MSHSAA teams) and reads that number off their page.
 
URL PATTERN (confirmed from a real captured page, not guessed):
    https://www.mshsaa.org/MySchool/Schedule.aspx?s={school_id}&alg=19&year=2026
    (alg=19 = 11-man football, same flag the main scoreboard scraper uses)
 
VARSITY-ONLY: the schedule page lists JV/Freshman games in the same table,
distinguished only by each row's data-level attribute (confirmed from CBC's
page: data-level="1" is varsity; other values are lower levels). Only
level="1" rows are used, exactly like the earlier CBC parsing exercise --
getting this wrong is exactly what produced the false "Edwardsville" result
that had to be corrected before.
 
OPPONENT IDENTIFICATION: an opponent cell with a MySchool/Schedule.aspx link
is an MSHSAA (in-state) team; one without a link is out-of-state. Only the
out-of-state ones are recorded here -- in-state opponents' records are
already fully known from build_district_points.py's own aggregation.
 
INPUT: resolved_team_ids.json -- {team_name: school_id}, the 57 in-state
teams known (from the games data + out_of_state_classifications.json) to
play at least one out-of-state opponent. This file is hand-built/curated,
not generated by this script -- 13 of its entries are manual IDs Tyler
supplied because mshsaa_schools.csv either used a different name (co-ops)
or was simply missing the school.
 
OUTPUT: out_of_state_records.json --
    {
      "Trinity Catholic (KY.)": {
        "wins": 3, "losses": 1, "record_text": "3-1",
        "source_team": "Christian Brothers College",
        "scraped_date": "2026-09-17"
      },
      ...
    }
If the same out-of-state opponent is found on more than one in-state team's
schedule (plays two different MSHSAA teams this season), and their shown
records DISAGREE, this is flagged with a warning printed to the console and
the higher game-count (more complete) record is kept -- but this should be
rare since all 57 pages are scraped in the same run.
 
NAME MATCHING: the out-of-state opponent's display text on the schedule
page must match out_of_state_classifications.json's keys EXACTLY for
build_district_points.py to pick this up (confirmed as a clean 59/59 match
earlier -- this script re-checks that at the end and prints anything that
doesn't line up, since a new season's schedule page could show slightly
different punctuation than what was hand-collected before).
 
Usage:
    python3 scrape_out_of_state_records.py
"""
 
import json
import re
import time
from datetime import date
 
import requests
from bs4 import BeautifulSoup
 
TEAM_IDS_PATH = "resolved_team_ids.json"
OOS_CLASS_PATH = "out_of_state_classifications.json"
OUTPUT_PATH = "out_of_state_records.json"
 
SCHEDULE_URL = "https://www.mshsaa.org/MySchool/Schedule.aspx?s={sid}&alg=19&year=2026"
REQUEST_DELAY = 0.5  # same courtesy delay as the main scraper
 
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Referer": "https://www.mshsaa.org/",
}
 
 
def build_session():
    from requests.adapters import HTTPAdapter
    try:
        from urllib3.util.retry import Retry
    except ImportError:
        from requests.packages.urllib3.util.retry import Retry
 
    session = requests.Session()
    retry = Retry(
        total=1, connect=1, read=1, backoff_factor=1.5,
        status_forcelist=[500, 502, 503, 504], raise_on_status=False,
    )
    adapter = HTTPAdapter(max_retries=retry, pool_connections=1, pool_maxsize=1)
    session.mount("https://", adapter)
    session.mount("http://", adapter)
    return session
 
 
def parse_varsity_opponents(html):
    """
    Returns a list of (opponent_name, is_mshsaa_team, wins, losses) for
    every varsity (data-level="1") row on a team's schedule page.
    Verified directly against CBC's real captured page: the td's id is
    ASP.NET-generated (e.g. "...ctl01_tdOpponent"), so match on a suffix,
    not an exact id.
    """
    soup = BeautifulSoup(html, "html.parser")
    results = []
 
    rows = soup.find_all("tr", id=lambda v: v and "trItem" in v, attrs={"data-level": "1"})
    for row in rows:
        opp_cell = row.find("td", id=lambda v: v and v.endswith("tdOpponent"))
        if opp_cell is None:
            continue
 
        link = opp_cell.find("a", href=lambda h: h and "/MySchool/Schedule.aspx" in h)
        is_mshsaa = link is not None
 
        text = opp_cell.get_text(" ", strip=True)
        # Strip a trailing "(W-L)" record off the end to isolate the name.
        record_match = re.search(r"\((\d+)-(\d+)\)\s*$", text)
        if record_match:
            wins, losses = int(record_match.group(1)), int(record_match.group(2))
            name = text[: record_match.start()].strip()
        else:
            wins, losses = None, None
            name = text.strip()
 
        # Drop a leading "at " (away-game marker) if present.
        name = re.sub(r"^at\s+", "", name).strip()
        # Collapse any internal whitespace runs (the real page has some,
        # e.g. "Class 6 State  Tournament" with a double space) before
        # checking for the state-tournament placeholder row.
        normalized = re.sub(r"\s+", " ", name)
 
        if normalized and "Tournament" not in normalized:
            results.append((normalized, is_mshsaa, wins, losses))
 
    return results
 
 
def normalize_state_suffix(name):
    """
    Normalizes the trailing state marker so schedule-page text can match
    out_of_state_classifications.json's keys despite inconsistent MSHSAA
    formatting -- confirmed necessary from real data: the schedule page
    shows "Trinity Catholic (KY)" and "Lipscomb Academy (Tenn.)" while the
    classification file (built from a different, earlier-hand-collected
    source) has "Trinity Catholic (KY.)" and "Lipscomb Academy (TN.)".
    Strips periods and expands a handful of observed full-name state
    abbreviations to their 2-letter form, then re-adds a trailing period
    consistently, so both sides of a match go through the same normalizer.
    """
    STATE_FULLNAME_TO_ABBR = {
        "Tenn": "TN", "Ill": "IL", "Ark": "AR", "Kan": "KS", "Kans": "KS",
        "Ky": "KY", "Neb": "NE", "Okla": "OK", "Ga": "GA", "Va": "VA",
    }
    m = re.search(r"\(([A-Za-z.]+)\)\s*$", name)
    if not m:
        return name  # no trailing state marker at all -- leave as-is
    raw_state = m.group(1).rstrip(".")
    state = STATE_FULLNAME_TO_ABBR.get(raw_state, raw_state.upper())
    base = name[: m.start()].strip()
    return f"{base} ({state}.)"
 
 
def scrape_team(session, team_name, school_id):
    url = SCHEDULE_URL.format(sid=school_id)
    try:
        resp = session.get(url, timeout=(10, 25), headers=HEADERS)
        resp.raise_for_status()
    except requests.RequestException as e:
        print(f"  FAILED {team_name} (id={school_id}): {e}")
        return []
 
    opponents = parse_varsity_opponents(resp.text)
    out_of_state = [
        (name, wins, losses) for name, is_mshsaa, wins, losses in opponents
        if not is_mshsaa
    ]
    return out_of_state
 
 
def main():
    team_ids = json.load(open(TEAM_IDS_PATH))
    oos_class_names = set(json.load(open(OOS_CLASS_PATH)).keys())
 
    session = build_session()
    records = {}
    conflicts = []
    no_record_shown = []
    today = date.today().isoformat()
 
    for i, (team_name, school_id) in enumerate(sorted(team_ids.items()), start=1):
        print(f"[{i}/{len(team_ids)}] Scraping {team_name} (id={school_id})...", end=" ")
        oos_opponents = scrape_team(session, team_name, school_id)
        print(f"{len(oos_opponents)} out-of-state opponent(s) found")
 
        for raw_opp_name, wins, losses in oos_opponents:
            # Match against out_of_state_classifications.json's actual key
            # if a normalized match exists, so a punctuation/abbreviation
            # difference doesn't silently create a second, unmatched entry.
            normalized = normalize_state_suffix(raw_opp_name)
            opp_name = normalized if normalized in oos_class_names else raw_opp_name
 
            if wins is None or losses is None:
                no_record_shown.append((team_name, opp_name))
                continue
 
            games_shown = wins + losses
            if opp_name in records:
                existing = records[opp_name]
                existing_games = existing["wins"] + existing["losses"]
                if (existing["wins"], existing["losses"]) != (wins, losses):
                    conflicts.append({
                        "opponent": opp_name,
                        "existing": f"{existing['wins']}-{existing['losses']} (from {existing['source_team']})",
                        "new": f"{wins}-{losses} (from {team_name})",
                    })
                    if games_shown <= existing_games:
                        continue  # keep the more complete record already stored
 
            records[opp_name] = {
                "wins": wins,
                "losses": losses,
                "record_text": f"{wins}-{losses}",
                "source_team": team_name,
                "scraped_date": today,
            }
 
        time.sleep(REQUEST_DELAY)
 
    with open(OUTPUT_PATH, "w") as f:
        json.dump(records, f, indent=2, sort_keys=True)
 
    print()
    print(f"Wrote {OUTPUT_PATH}")
    print(f"Out-of-state opponents with a record found: {len(records)}")
 
    if conflicts:
        print(f"\n*** {len(conflicts)} CONFLICT(S) -- same opponent, different records on different pages: ***")
        for c in conflicts:
            print(f"  {c['opponent']}: kept {c['existing']}  vs  saw {c['new']}")
 
    if no_record_shown:
        print(f"\n{len(no_record_shown)} out-of-state opponent(s) found with no (W-L) shown on the page:")
        for team, opp in no_record_shown:
            print(f"  {team} -> {opp}")
 
    scraped_names = set(records.keys())
    unmatched = scraped_names - oos_class_names
    if unmatched:
        print(f"\n*** {len(unmatched)} scraped name(s) DON'T match out_of_state_classifications.json exactly -- these won't be picked up by build_district_points.py until reconciled: ***")
        for n in sorted(unmatched):
            print(f"  {n!r}")
 
    missing = oos_class_names - scraped_names
    if missing:
        print(f"\n{len(missing)} out-of-state team(s) in the classification file that this run didn't find a record for (may not have played yet, or their in-state opponent's game hasn't posted):")
        for n in sorted(missing):
            print(f"  {n}")
 
 
if __name__ == "__main__":
    main()
